#!/bin/bash
# test_comment_yap_advisory.sh — coverage for the comment-yap advisory (issue #1141).
#
# Synthesizes Claude Code PreToolUse(Edit|Write) payloads and asserts:
#   advise → exit 0 + stderr carries the advisory marker
#   silent → exit 0 + stderr empty
#
# The two regression arms that matter most are negatives, not positives: a
# hook that fires on a good long comment is worse than one that never fires,
# so a real 68-line sibling docstring is pinned as silent, and the whole
# repo's python is swept for false positives.
#
# Usage: bash tests/hooks/advisory-nudge/test_comment_yap_advisory.sh
# Exit:  0 = all pass; 1 = at least one fail

set +e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../../.." && pwd)"
HOOK="$ROOT_DIR/hooks/advisory-nudge/comment-yap-advisory/impl.py"
SIBLING="$ROOT_DIR/hooks/advisory-nudge/secret-print-redaction-advisory/impl.py"

if [ ! -f "$HOOK" ]; then
  echo "FAIL: hook not found: $HOOK" >&2
  exit 1
fi

PASS=0
FAIL=0
FAILED_NAMES=()

# run_case <name> <advise|silent> <file_path> <content>
run_case() {
  local name="$1" expected="$2" file_path="$3" content="$4"

  local payload
  payload=$(python3 -c '
import json, sys
print(json.dumps({
    "tool_name": "Write",
    "tool_input": {"file_path": sys.argv[1], "content": sys.argv[2]},
}))' "$file_path" "$content")

  local err_file rc stderr_text
  err_file=$(mktemp)
  # `env -u`: these cases pin the DEFAULT thresholds, so an inherited
  # override from the ambient shell must not silently retune the assertion.
  printf '%s' "$payload" | env -u PRAXIS_YAP_PREAMBLE_LINES \
    -u PRAXIS_YAP_SPRAWL_LINES -u PRAXIS_YAP_MAX_BYTES \
    python3 "$HOOK" >/dev/null 2>"$err_file"
  rc=$?
  stderr_text=$(cat "$err_file")
  rm -f "$err_file"

  local ok=1
  [ "$rc" -eq 0 ] || ok=0
  case "$expected" in
    advise) [[ "$stderr_text" == *"[comment-yap-advisory]"* ]] || ok=0 ;;
    silent) [ -z "$stderr_text" ] || ok=0 ;;
  esac

  if [ "$ok" -eq 1 ]; then
    PASS=$((PASS + 1))
    echo "  ok   $name"
  else
    FAIL=$((FAIL + 1))
    FAILED_NAMES+=("$name")
    echo "  FAIL $name (rc=$rc, expected=$expected)"
    [ -n "$stderr_text" ] && echo "$stderr_text" | head -4 | sed 's/^/       /'
  fi
}

# Repeat a single line N times, newline-joined.
repeat_line() {
  python3 -c 'import sys; print("\n".join([sys.argv[1]] * int(sys.argv[2])))' "$1" "$2"
}

echo "== detectors fire =="

# D2 — an unanchored file header. The post's "50 lines at the top of a file".
run_case "D2 unanchored header" advise "mod.py" \
  "$(repeat_line '# We now need to make sure the thing we are doing is the right thing' 30)
x = 1"

# D2 — a C-style block comment carries the same shape.
run_case "D2 block comment" advise "mod.c" \
  "/*
$(repeat_line ' * and then we consider what happens when the caller wants something' 30)
 */
int x;"

# D1 — the post's "30-line comment above a simple type".
run_case "D1 preamble over type alias" advise "mod.ts" \
  "$(repeat_line '// here we are going to be defining the type we will use later on' 14)
type Foo = string;"

# D1 — attachment is required: the same run over a blank line is only D2's
# business, and 14 lines is below the sprawl threshold.
run_case "D1 needs attachment" silent "mod.ts" \
  "$(repeat_line '// here we are going to be defining the type we will use later on' 14)

type Foo = string;"

echo "== anchoring keeps a long comment silent =="

# The 2-signal AND gate: same volume, but every line cites something.
run_case "anchored long header" silent "mod.py" \
  "$(repeat_line '# See issue #1141 and `safe_tokenize` in hooks/_lib/_hook_utils.py' 30)
x = 1"

# The pinned negative: a real, useful 68-line module docstring from a sibling
# hook. If this ever fires, the anchor model has regressed.
run_case "sibling 68-line docstring" silent "impl.py" "$(cat "$SIBLING")"

# The hook must be silent on its own source.
run_case "own source" silent "impl.py" "$(cat "$HOOK")"

echo "== exclusions =="

run_case "prose file (unmapped ext)" silent "notes.md" \
  "$(repeat_line 'we are going to write a great many words about the thing here' 40)"

run_case "unknown extension" silent "data.xyz" \
  "$(repeat_line '# We now need to make sure the thing we are doing is the right thing' 30)
x = 1"

run_case "license header" silent "mod.py" \
  "# Copyright 2026 The Praxis Authors
$(repeat_line '# distributed under the terms described in the accompanying notice' 30)
x = 1"

run_case "generated marker" silent "mod.go" \
  "// Code generated by protoc-gen-go. DO NOT EDIT.
$(repeat_line '// this file was produced by a generator and should not be touched' 30)
var x int"

run_case "commented-out code" silent "mod.py" \
  "$(repeat_line '# result = compute(value)' 30)
x = 1"

run_case "trailing comments form no run" silent "mod.py" \
  "$(repeat_line 'x = 1  # we now consider the thing that happens when we do this' 30)"

run_case "short comment" silent "mod.py" \
  "$(repeat_line '# a brief note about the thing' 5)
x = 1"

echo "== parser regressions =="

# A docstring documents its enclosing function, so D1's subject span says
# nothing about proportion. Only D2 applies.
run_case "docstring exempt from D1" silent "mod.py" \
  'def f(argv):
    """Return a value.

'"$(repeat_line '    we walk the tokens and then decide what to do with each one' 12)"'
    """
    return 1'

# A multi-line string opener whose line ends in a backslash continuation
# must not leave the scanner reading real code as one enormous comment.
run_case "string opener with continuation" silent "mod.py" \
  'MSG = """\
some message text
"""


def f():
    return 1'

# A delimiter nested inside the other quote style is a literal, not an opener.
run_case "delimiter inside a literal" silent "mod.py" \
  "DELIMS = ('\''\"\"\"'\'', \"'''\")


def f():
    return 1"

# Past the run-length cap every counter freezes together, so an enormous
# unanchored run still fires rather than suppressing itself on arithmetic.
# The payload is built inside python: 5000 lines exceed ARG_MAX through
# `run_case`'s argv, and the short line keeps it under the 256 KiB byte cap
# that would otherwise return before the scan and mask what this pins.
capped_run_payload=$(python3 -c '
import json
print(json.dumps({
    "tool_name": "Write",
    "tool_input": {
        "file_path": "mod.py",
        "content": "\n".join(["# and then we consider the thing"] * 5000) + "\nx = 1",
    },
}))')
err_file=$(mktemp)
printf '%s' "$capped_run_payload" | python3 "$HOOK" >/dev/null 2>"$err_file"
if grep -q "4096 comment lines" "$err_file"; then
  PASS=$((PASS + 1)); echo "  ok   run past the length cap freezes at 4096 and still fires"
else
  FAIL=$((FAIL + 1)); FAILED_NAMES+=("run length cap")
  echo "  FAIL run past the length cap"
fi
rm -f "$err_file"

# A triple quote after a line ending mid-expression is fixture data.
run_case "triple quote as an operand" silent "mod.py" \
  'p.write_text(
    """---
'"$(repeat_line 'name: value' 12)"'
---
""",
)'

echo "== fail-open and payload guards =="

# fail_open_case <name> <payload>
fail_open_case() {
  local name="$1" payload="$2"
  local rc stderr_text err_file
  err_file=$(mktemp)
  printf '%s' "$payload" | python3 "$HOOK" >/dev/null 2>"$err_file"
  rc=$?
  stderr_text=$(cat "$err_file")
  rm -f "$err_file"
  if [ "$rc" -eq 0 ] && [[ "$stderr_text" != *"[comment-yap-advisory]"* ]]; then
    PASS=$((PASS + 1)); echo "  ok   $name"
  else
    FAIL=$((FAIL + 1)); FAILED_NAMES+=("$name"); echo "  FAIL $name (rc=$rc)"
  fi
}

fail_open_case "malformed json" 'not json at all'
fail_open_case "non-dict payload" '["a"]'
fail_open_case "unrelated tool" '{"tool_name":"Bash","tool_input":{"command":"ls"}}'
fail_open_case "missing file_path" '{"tool_name":"Write","tool_input":{"content":"# x"}}'
fail_open_case "empty content" '{"tool_name":"Write","tool_input":{"file_path":"a.py","content":"   "}}'

echo "== Edit scans new_string =="

edit_payload=$(python3 -c '
import json
print(json.dumps({
    "tool_name": "Edit",
    "tool_input": {
        "file_path": "mod.py",
        "old_string": "x = 1",
        "new_string": "\n".join(
            ["# We now need to make sure the thing we do is the right thing"] * 30
        ) + "\nx = 1",
    },
}))')
err_file=$(mktemp)
printf '%s' "$edit_payload" | python3 "$HOOK" >/dev/null 2>"$err_file"
if grep -q "\[comment-yap-advisory\]" "$err_file"; then
  PASS=$((PASS + 1)); echo "  ok   Edit new_string advises"
else
  FAIL=$((FAIL + 1)); FAILED_NAMES+=("Edit new_string advises"); echo "  FAIL Edit new_string advises"
fi
rm -f "$err_file"

echo "== env overrides =="

# The byte cap returns before scanning: the same yap goes silent above it.
capped_payload=$(python3 -c '
import json
print(json.dumps({
    "tool_name": "Write",
    "tool_input": {
        "file_path": "mod.py",
        "content": "\n".join(
            ["# We now need to make sure the thing we do is the right thing"] * 30
        ) + "\nx = 1",
    },
}))')
err_file=$(mktemp)
printf '%s' "$capped_payload" | PRAXIS_YAP_MAX_BYTES=10 python3 "$HOOK" >/dev/null 2>"$err_file"
if [ ! -s "$err_file" ]; then
  PASS=$((PASS + 1)); echo "  ok   PRAXIS_YAP_MAX_BYTES caps the scan"
else
  FAIL=$((FAIL + 1)); FAILED_NAMES+=("byte cap"); echo "  FAIL PRAXIS_YAP_MAX_BYTES caps the scan"
fi
rm -f "$err_file"

# A garbage override falls back to the default rather than disabling the hook.
err_file=$(mktemp)
printf '%s' "$capped_payload" | PRAXIS_YAP_SPRAWL_LINES=nonsense python3 "$HOOK" >/dev/null 2>"$err_file"
if grep -q "\[comment-yap-advisory\]" "$err_file"; then
  PASS=$((PASS + 1)); echo "  ok   garbage override falls back to default"
else
  FAIL=$((FAIL + 1)); FAILED_NAMES+=("garbage override"); echo "  FAIL garbage override falls back to default"
fi
rm -f "$err_file"

# Raising the threshold above the run length silences it. The run is left
# detached by a blank line so only D2 is in play — an attached run of this
# length is D1's, and would still fire at the default preamble threshold.
detached_payload=$(python3 -c '
import json
print(json.dumps({
    "tool_name": "Write",
    "tool_input": {
        "file_path": "mod.py",
        "content": "\n".join(
            ["# We now need to make sure the thing we do is the right thing"] * 30
        ) + "\n\nx = 1",
    },
}))')
err_file=$(mktemp)
printf '%s' "$detached_payload" | python3 "$HOOK" >/dev/null 2>"$err_file"
if grep -q "\[comment-yap-advisory\]" "$err_file"; then
  PASS=$((PASS + 1)); echo "  ok   detached run still fires D2 at the default"
else
  FAIL=$((FAIL + 1)); FAILED_NAMES+=("detached default"); echo "  FAIL detached run fires D2 at the default"
fi
rm -f "$err_file"

err_file=$(mktemp)
printf '%s' "$detached_payload" | PRAXIS_YAP_SPRAWL_LINES=99 python3 "$HOOK" >/dev/null 2>"$err_file"
if [ ! -s "$err_file" ]; then
  PASS=$((PASS + 1)); echo "  ok   PRAXIS_YAP_SPRAWL_LINES raises the threshold"
else
  FAIL=$((FAIL + 1)); FAILED_NAMES+=("sprawl override"); echo "  FAIL PRAXIS_YAP_SPRAWL_LINES raises the threshold"
fi
rm -f "$err_file"

echo "== fire-ledger instrumentation (issue #740 single-event RICH) =="

# The hook signals on stderr while exiting 0, so @fail_open's coarse path
# records every engagement as "pass". Without a RICH record no ledger query
# could say whether it had ever advised — and an unmeasurable hook cannot be
# scored by the prune audit. PRAXIS_FIRE_TELEMETRY_FILE isolates the probe so
# it never touches the production ledger, and the opt-out is unset so an
# inherited DISABLE=1 cannot make an empty ledger read as "never fired".
ledger_out=$(python3 - "$HOOK" <<'PY'
import glob, json, os, subprocess, sys, tempfile

hook = sys.argv[1]
ledger = os.path.join(tempfile.mkdtemp(), "fire.jsonl")
env = dict(os.environ)
env["PRAXIS_FIRE_TELEMETRY_FILE"] = ledger
env.pop("PRAXIS_FIRE_TELEMETRY_DISABLE", None)

YAP = "\n".join(["# We now need to make sure the thing we do is the right thing"] * 30) + "\nx = 1"


def run(content, tool="Write", session_id="sess-abc", disable=False):
    payload = {"tool_name": tool, "tool_input": {"file_path": "mod.py"}}
    payload["tool_input"]["content" if tool == "Write" else "new_string"] = content
    if session_id is not None:
        payload["session_id"] = session_id
    run_env = dict(env)
    if disable:
        run_env["PRAXIS_FIRE_TELEMETRY_DISABLE"] = "1"
    before = read()
    result = subprocess.run(
        [sys.executable, hook], input=json.dumps(payload),
        capture_output=True, text=True, env=run_env,
    )
    return bool(result.stderr.strip()), read()[len(before):]


def read():
    if not os.path.exists(ledger):
        return []
    with open(ledger, encoding="utf-8") as handle:
        return [json.loads(line) for line in handle if line.strip()]


def read_counts():
    """A `pass` is counted, not appended (issue #1238), so it lands in the
    counter siblings beside the override rather than in the override itself."""
    rows = []
    for path in sorted(glob.glob(os.path.join(os.path.dirname(ledger), "fire-counts-*.jsonl"))):
        with open(path, encoding="utf-8") as handle:
            rows.extend(json.loads(line) for line in handle if line.strip())
    return rows


failures = []


def check(name, condition):
    if not condition:
        failures.append(name)


advised, rows = run(YAP)
check("advise emits stderr", advised)
# Exactly one row proves the coarse duplicate was suppressed: unsuppressed,
# aggregate_fires() would sum this single engagement as fires=2, advise=1,
# pass=1 and corrupt the very rate the ledger exists to report.
check("advise writes exactly one record (coarse suppressed)", len(rows) == 1)
if rows:
    row = rows[0]
    check("record is rich", row.get("granularity") == "rich")
    check("decision is advise", row.get("decision") == "advise")
    check("hook name recorded", row.get("hook") == "comment-yap-advisory")
    check("role recorded", row.get("role") == "advisory-nudge")
    check("session_id attributed", row.get("session_id") == "sess-abc")
    check("tool attributed", row.get("tool") == "Write")

advised, rows = run("x = 1\n")
check("silent run emits no stderr", not advised)
# A silent pass is exactly what the coarse record already says, so the hook
# must not add a second one. It is counted rather than appended, so the row
# lives in the counter sibling and carries a count of 1.
counts = read_counts()
check("silent run writes no ledger row", len(rows) == 0)
check("silent run counts one coarse pass", len(counts) == 1
      and counts[0].get("granularity") == "coarse"
      and counts[0].get("decision") == "pass"
      and counts[0].get("count") == 1)

advised, rows = run(YAP, tool="Edit")
check("Edit tool attributed", len(rows) == 1 and rows[0].get("tool") == "Edit")

# A missing session_id must cost per-session attribution only, never the
# decision count itself (the lesson of the CodeRabbit finding on PR #796).
advised, rows = run(YAP, session_id=None)
check("missing session_id still records the decision",
      len(rows) == 1 and rows[0].get("decision") == "advise"
      and rows[0].get("session_id") == "")

# Telemetry is opt-out, and the opt-out must not disturb the advisory itself.
advised, rows = run(YAP, disable=True)
check("DISABLE=1 still advises", advised)
check("DISABLE=1 writes nothing", len(rows) == 0 and len(read_counts()) == 1)

print("FAILURES:" + ",".join(failures) if failures else "ALL_OK")
PY
)
if [ "$ledger_out" = "ALL_OK" ]; then
  PASS=$((PASS + 1)); echo "  ok   fire-ledger records one rich 'advise' and suppresses the coarse duplicate"
else
  FAIL=$((FAIL + 1)); FAILED_NAMES+=("fire ledger")
  echo "  FAIL fire-ledger instrumentation — $ledger_out"
fi

echo "== repo-wide false-positive sweep =="

# The hook runs on every Write and Edit, so a false positive is a tax on
# every session. The repo's own hand-written python is the corpus.
sweep_out=$(python3 - "$HOOK" <<'PY'
import glob, json, subprocess, sys

hook = sys.argv[1]
files = sorted(
    set(glob.glob("hooks/*/*/impl.py"))
    | set(glob.glob("hooks/_lib/*.py"))
    | set(glob.glob("scripts/*.py"))
    | set(glob.glob("tests/**/*.py", recursive=True))
)
fired = []
for path in files:
    with open(path, encoding="utf-8") as handle:
        content = handle.read()
    payload = json.dumps(
        {"tool_name": "Write", "tool_input": {"file_path": path, "content": content}}
    )
    result = subprocess.run(
        [sys.executable, hook], input=payload, capture_output=True, text=True
    )
    if result.stderr.strip():
        fired.append(path)
print(f"{len(files)} {len(fired)}")
for path in fired:
    print("   fired:", path)
PY
)
sweep_counts=$(echo "$sweep_out" | head -1)
swept=$(echo "$sweep_counts" | cut -d' ' -f1)
fired_n=$(echo "$sweep_counts" | cut -d' ' -f2)
if [ "$swept" -gt 100 ] && [ "$fired_n" -eq 0 ]; then
  PASS=$((PASS + 1)); echo "  ok   swept $swept repo python files, 0 false positives"
else
  FAIL=$((FAIL + 1)); FAILED_NAMES+=("repo sweep")
  echo "  FAIL swept $swept files, $fired_n fired"
  echo "$sweep_out" | tail -n +2
fi

echo
echo "PASS=$PASS FAIL=$FAIL"
if [ "$FAIL" -gt 0 ]; then
  printf 'failed: %s\n' "${FAILED_NAMES[*]}" >&2
  exit 1
fi
exit 0
