#!/usr/bin/env python3
"""Generate platform-specific plugin manifests from a canonical base.

Reads:
  manifests/plugin.base.json     — shared metadata (name, description,
                                   author, repository, homepage, category,
                                   keywords)
  manifests/platforms/*.json     — per-platform output declarations
  VERSION                        — authoritative version string
  hooks/manifest.json            — canonical hook registry (ADR-0001 §2.5);
                                   each entry may carry a `hosts` whitelist
                                   that is filtered per platform host_id at
                                   build time

Writes (generated artifacts, committed to the repo):
  .claude-plugin/plugin.json
  .claude-plugin/marketplace.json
  .claude-plugin/hooks/hooks.json
  .agents/plugins/marketplace.json
  plugins/praxis/.codex-plugin/plugin.json
  plugins/praxis/.codex-plugin/hooks/hooks.json
  .cursor-plugin/plugin.json
  .cursor-plugin/hooks/hooks.json
  plugin.json                    — Agent Plugins 1.0.0 portable manifest
                                   (agent-plugins.org) for the hosts whose
                                   plugin root IS the repo root. Codex's is
                                   plugins/praxis/, so Codex does not see
                                   this file and is out of scope here.
  hooks/<name>{suffix}.sh        — runtime wrapper(s), one per unique
                                   (name, wrapper_suffix) pair; tracked
                                   so marketplace installs (which do not
                                   run this build) get a working tree
  docs/hook-operating-matrix.md  - generated hook operating surface summary

Also creates `plugins/praxis/{skills,hooks,scripts}` as symlinks into the
repo root so the Codex adapter shell forwards to the common runtime
directories without duplicating source.

Idempotent. Re-running on a clean tree produces no diff — that invariant
is what `scripts/check-plugin-manifests.py` verifies in CI.

Wrapper emission contract (ADR-0001 §2.3, §5.2):
  Every manifest entry without a `body` field is a Python-impl hook and
  needs a `hooks/<name>{suffix}.sh` wrapper that execs
  `hooks/<role>/<name>/impl.py`. Entries with `body: "impl.sh"` are
  body-as-sh hooks and need a `hooks/<name>.sh` wrapper that execs
  `hooks/<role>/<name>/impl.sh`. Multi-event hooks (e.g. pre-edit-md-
  escape-advisory) declare a `wrapper_suffix` ("-pre" / "-post") so each
  registered event gets its own wrapper file with the dispatch arg baked
  in; the `args` field of the entry is included in the wrapper body.
"""
from __future__ import annotations

import copy
import json
import os
import re
import shlex
import sys
import unicodedata
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
MANIFESTS_DIR = REPO_ROOT / "manifests"
PLATFORMS_DIR = MANIFESTS_DIR / "platforms"
ADAPTER_SHELL = REPO_ROOT / "plugins" / "praxis"
FORWARDED_DIRS = ("skills", "hooks", "scripts")
HOOKS_DIR = REPO_ROOT / "hooks"
DOCS_HOOK_DIR = REPO_ROOT / "docs" / "hook"
HOOK_OPERATING_MATRIX_PATH = REPO_ROOT / "docs" / "hook-operating-matrix.md"
BYPASS_VARS_DOC = REPO_ROOT / "docs" / "bypass-vars.md"
SECURITY_DOC = REPO_ROOT / "SECURITY.md"

sys.path.insert(0, str(REPO_ROOT / "scripts"))
from constants import NON_HOOK_DOCS, OPT_IN_HOOKS  # noqa: E402
MANIFEST_PATH = HOOKS_DIR / "manifest.json"

# Agent Plugins portable manifest schema, pinned to the only published spec
# version (1.1.0 is a working draft). Clients find this file by path —
# plugin.json at the plugin root — and read $schema only to pick which local
# validation rules to apply, never to fetch anything. An unsupported version
# is therefore fatal on its own: "A missing or unsupported `$schema` rejects
# the plugin" (agent-plugins.org/client-implementers/loading-and-discovery).
# The spec defines no fallback, so a newer pin does not defer to the host's
# own manifest; it just fails to load.
AGENT_PLUGIN_SCHEMA_URI = "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json"

# docs/hook/<name>.md is a 1-line redirect stub to the role-based spec
# (ADR-0001 §337-338): the flat docs/hook/ URLs must keep resolving for one
# release cycle after the per-role migration. Generated per hook dir, #606.
DOC_STUB_TEMPLATE = (
    "> Moved to [hooks/{role}/{name}/spec.md]"
    "(../../hooks/{role}/{name}/spec.md)\n"
)


# Wrapper body templates — ADR-0001 §2.3.
# Python wrappers delegate to <role>/<name>/impl.py; body-as-sh wrappers
# delegate to <role>/<name>/impl.sh. Both live at hooks/<name>{suffix}.sh
# so the emitted command path
#   ${CLAUDE_PLUGIN_ROOT}/hooks/<name>{suffix}.sh
# stays byte-identical to the pre-Phase-2 baseline.
WRAPPER_PY_TEMPLATE = """\
#!/bin/sh
# AUTO-GENERATED by scripts/build-plugin-manifests.py — DO NOT EDIT
# Source: hooks/{role}/{name}/impl.py  (see ADR-0001 §2.3)
set +e
command -v python3 >/dev/null 2>&1 || exit 0
# A missing impl makes python3 exit 2, which is this repo's deny code — the
# launcher would hand the host a block nobody decided. Absent impl means the
# hook cannot judge, so it must not judge. Normalizing every non-zero code
# instead would swallow the deliberate exit 2 of every gate.
IMPL="$(dirname "$0")/{role}/{name}/impl.py"
[ -f "$IMPL" ] || exit 0
exec python3 "$IMPL" {baked_args}"$@"
"""

WRAPPER_SH_TEMPLATE = """\
#!/bin/sh
# AUTO-GENERATED by scripts/build-plugin-manifests.py — DO NOT EDIT
# Source: hooks/{role}/{name}/impl.sh  (see ADR-0001 §2.3)
# Direct exec so the impl's own #!/bin/bash shebang is honored —
# `exec sh impl.sh` would re-route through /bin/sh (dash on Debian)
# and break Bash-only syntax like [[ ... =~ ... ]] used in
# retrospect-mix-check / codex-review-route / strike-counter.
# Absent impl means the hook cannot judge, so it must not judge — same
# contract as the python wrapper above.
IMPL="$(dirname "$0")/{role}/{name}/impl.sh"
[ -f "$IMPL" ] || exit 0
exec "$IMPL" "$@"
"""

# ADR-0002 — single-process dispatch runner wrapper. A dispatch-group hooks.json
# node execs this once (with `<event> <matcher> <host>` args) instead of one
# wrapper per member; _dispatch.py imports each member's impl.py in-process.
WRAPPER_DISPATCH_TEMPLATE = """\
#!/bin/sh
# AUTO-GENERATED by scripts/build-plugin-manifests.py — DO NOT EDIT
# Source: hooks/_lib/_dispatch.py  (see ADR-0002 dispatch consolidation)
set +e
command -v python3 >/dev/null 2>&1 || exit 0
# See the per-hook wrapper above: a missing impl exits 2, which the host reads
# as deny. A dispatch group that cannot start must fall through, not block.
IMPL="$(dirname "$0")/_lib/_dispatch.py"
[ -f "$IMPL" ] || exit 0
exec python3 "$IMPL" "$@"
"""
DISPATCH_WRAPPER_NAME = "_dispatch.sh"

# argv sentinel rendered into a dispatcher node's command when the group has no
# matcher (Stop, SessionStart, UserPromptSubmit — their manifest entries carry
# no matcher key, so the group identity is (event, None)). argv carries only
# strings; an f-string render of None would pass the literal "None", which the
# runtime's exact-match filter maps to zero members — silently disabling the
# whole group. Kept in sync with hooks/_lib/_dispatch.py NO_MATCHER_ARG
# (check-plugin-manifests.py Rule 14 pins the pairing).
DISPATCH_NO_MATCHER_ARG = "-"


# ---------------------------------------------------------------------------
# Manifest loading
# ---------------------------------------------------------------------------

def load_base() -> dict:
    base = json.loads((MANIFESTS_DIR / "plugin.base.json").read_text())
    base["version"] = (REPO_ROOT / "VERSION").read_text().strip()
    return base


def load_manifest() -> dict:
    return json.loads(MANIFEST_PATH.read_text())


# ---------------------------------------------------------------------------
# Manifest schema validation (#1173)
#
# hooks/manifest.schema.json is the structural contract for the canonical hook
# registry. `jsonschema` is not importable here or in CI (scripts/ are
# stdlib-only by repo precedent), so schema_validation_errors() below is a
# stdlib walker driven BY the schema file — the schema stays the single source
# of truth; nothing here hardcodes the manifest's shape. It lives in this
# module (not the check script) so BOTH consumers run it: build refuses to
# render from a malformed manifest, and check-plugin-manifests.py runs the
# same gate before its numbered rules.
# ---------------------------------------------------------------------------

SCHEMA_PATH = HOOKS_DIR / "manifest.schema.json"

# The exact JSON-Schema subset the walker enforces. Anything else appearing in
# the schema file is rejected up front by assert_schema_supported() — an
# unsupported keyword must fail loud, never be silently unenforced.
_SUPPORTED_SCHEMA_KEYWORDS = frozenset({
    "$schema", "$id", "title", "description",
    "type", "enum", "required", "properties", "additionalProperties",
    "items", "minimum", "minItems", "minLength",
})
_SUPPORTED_SCHEMA_TYPES = {
    "object": dict,
    "array": list,
    "string": str,
    "integer": int,
    "boolean": bool,
}

# dict.get(key) returns None for BOTH an absent key and an explicit JSON
# `null` value — `schema.get("type") is not None` can't tell them apart, so
# an explicit `"type": null` silently took the "no type constraint" branch
# instead of failing (review round 2, Codex finding 2). This sentinel makes
# "absent" and "present-but-null" distinguishable at the .get() call site.
_ABSENT = object()


def load_schema() -> dict:
    return json.loads(SCHEMA_PATH.read_text())


def assert_schema_supported(schema, spath: str = "#") -> None:
    """Fail loud (ValueError) when the schema steps outside the walker's subset.

    Guards the guard: an unsupported `type` value ("number", or the list form)
    would crash the walker mid-validation with a KeyError/TypeError, and an
    unsupported constraint keyword (pattern, maxLength, uniqueItems, $ref, …)
    would be SILENTLY unenforced — the exact failure mode the schema gate
    exists to eliminate. Walks the whole schema (not just instance-reachable
    nodes) so a bad keyword under an optional property is caught too.
    """
    if not isinstance(schema, dict):
        raise ValueError(
            f"hooks/manifest.schema.json {spath}: schema node must be an object, "
            f"got {type(schema).__name__}"
        )
    unknown = sorted(set(schema) - _SUPPORTED_SCHEMA_KEYWORDS)
    if unknown:
        raise ValueError(
            f"hooks/manifest.schema.json {spath}: unsupported schema keyword(s) "
            f"{unknown} — extend schema_validation_errors() in the same commit "
            "before using them"
        )
    schema_type = schema.get("type", _ABSENT)
    if schema_type is not _ABSENT and (
        not isinstance(schema_type, str)  # covers explicit null and the list form
        or schema_type not in _SUPPORTED_SCHEMA_TYPES
    ):
        raise ValueError(
            f"hooks/manifest.schema.json {spath}: unsupported type "
            f"{schema_type!r} (supported: {sorted(_SUPPORTED_SCHEMA_TYPES)})"
        )
    if "enum" in schema and (
        not isinstance(schema["enum"], list) or not schema["enum"]
    ):
        raise ValueError(
            f"hooks/manifest.schema.json {spath}: enum must be a non-empty array"
        )
    if schema.get("additionalProperties") not in (None, False):
        raise ValueError(
            f"hooks/manifest.schema.json {spath}: additionalProperties must be "
            "false or absent (subschema form is unsupported)"
        )
    if "required" in schema and not (
        isinstance(schema["required"], list)
        and all(isinstance(k, str) for k in schema["required"])
    ):
        raise ValueError(
            f"hooks/manifest.schema.json {spath}: required must be an array "
            "of strings"
        )
    props = schema.get("properties", {})
    if not isinstance(props, dict):
        raise ValueError(
            f"hooks/manifest.schema.json {spath}: properties must be an object"
        )
    for key, subschema in props.items():
        assert_schema_supported(subschema, f"{spath}/properties/{key}")
    if "items" in schema:
        assert_schema_supported(schema["items"], f"{spath}/items")


def schema_validation_errors(instance, schema, path: str = "$") -> list[str]:
    """Validate `instance` against the JSON-Schema subset the manifest schema uses.

    Subset limitation: only the keywords in _SUPPORTED_SCHEMA_KEYWORDS are
    enforced — type (object/array/string/integer/boolean), enum, required,
    properties, additionalProperties (false), items, minimum, minItems,
    minLength; $schema/$id/title/description are documentation and ignored.
    assert_schema_supported() rejects anything else up front, so a keyword
    can never be silently unenforced.
    """
    errs: list[str] = []
    if "enum" in schema:
        if instance not in schema["enum"]:
            errs.append(f"{path}: {instance!r} is not one of {schema['enum']!r}")
        return errs
    schema_type = schema.get("type", _ABSENT)
    if schema_type is not _ABSENT:
        # assert_schema_supported() already rejected a non-string/unknown
        # type (null included) before this walker ever runs, so schema_type
        # is guaranteed to be a valid key here — no separate null check
        # needed on this side.
        if schema_type == "integer":
            # Draft 2020-12: "integer" accepts any JSON number with zero
            # fractional part (e.g. 1.0), not only a JSON-encoded integer
            # literal — json.loads("1.0") is a Python float, so a bare
            # isinstance(instance, int) rejected a spec-valid value (review
            # round 2, Codex finding 3). bool is still excluded: it is a
            # Python int subclass, but JSON Schema keeps boolean and
            # integer distinct.
            is_integer = (
                isinstance(instance, int) and not isinstance(instance, bool)
            ) or (isinstance(instance, float) and instance.is_integer())
            if not is_integer:
                errs.append(
                    f"{path}: expected integer, got {type(instance).__name__}"
                )
                return errs
        else:
            py_type = _SUPPORTED_SCHEMA_TYPES[schema_type]
            # bool is a subclass of int in Python; JSON Schema keeps them distinct.
            if not isinstance(instance, py_type) or (
                py_type is int and isinstance(instance, bool)
            ):
                errs.append(
                    f"{path}: expected {schema_type}, got {type(instance).__name__}"
                )
                return errs
    if isinstance(instance, dict):
        props = schema.get("properties", {})
        for key in schema.get("required", []):
            if key not in instance:
                errs.append(f"{path}: missing required key {key!r}")
        if schema.get("additionalProperties") is False:
            for key in sorted(set(instance) - set(props)):
                errs.append(f"{path}: unknown key {key!r}")
        for key, subschema in props.items():
            if key in instance:
                errs.extend(
                    schema_validation_errors(instance[key], subschema, f"{path}.{key}")
                )
    elif isinstance(instance, list):
        if "minItems" in schema and len(instance) < schema["minItems"]:
            errs.append(
                f"{path}: needs at least {schema['minItems']} item(s), "
                f"got {len(instance)}"
            )
        items_schema = schema.get("items")
        if items_schema is not None:
            for i, element in enumerate(instance):
                errs.extend(
                    schema_validation_errors(element, items_schema, f"{path}[{i}]")
                )
    elif isinstance(instance, str):
        if "minLength" in schema and len(instance) < schema["minLength"]:
            errs.append(
                f"{path}: string shorter than minLength {schema['minLength']}"
            )
    elif isinstance(instance, bool):
        pass
    elif isinstance(instance, (int, float)):
        # Mirrors the integer-acceptance widening above: an integral float
        # (e.g. timeout: 30.0) must still be checked against "minimum".
        if "minimum" in schema and instance < schema["minimum"]:
            errs.append(f"{path}: {instance} is below minimum {schema['minimum']}")
    return errs


def manifest_schema_drifts(manifest) -> list[str]:
    """Schema-gate drift strings for hooks/manifest.json (#1173).

    Each error names the file, the JSON path (with the hook entry's `name`
    appended when the path points into hooks[N]), and the offending key.
    Never raises on a malformed MANIFEST — a top-level array (or any other
    wrong shape) must come back as a diagnostic string, not the AttributeError
    the gate exists to eliminate; only a malformed SCHEMA raises (ValueError
    from assert_schema_supported — developer error, fail loud).
    """
    schema = load_schema()
    assert_schema_supported(schema)
    # Entry-name labels only make sense when the manifest is shaped well
    # enough to have a hooks array; validation itself never needs them.
    hooks_list = manifest.get("hooks") if isinstance(manifest, dict) else None
    if not isinstance(hooks_list, list):
        hooks_list = []
    out: list[str] = []
    for err in schema_validation_errors(manifest, schema):
        label = ""
        m = re.match(r"\$\.hooks\[(\d+)\]", err)
        if m:
            idx = int(m.group(1))
            if idx < len(hooks_list) and isinstance(hooks_list[idx], dict):
                name = hooks_list[idx].get("name")
                if isinstance(name, str):
                    label = f" (entry {name!r})"
        out.append(f"SCHEMA hooks/manifest.json {err}{label}")

    # Semantic gate: dispatch-group membership is structural (a hook's own
    # (event, matcher) matching a `dispatch_groups` entry — see
    # filter_hooks_for_host), so the JSON-Schema subset above, which
    # validates `hooks[]` and `dispatch_groups[]` independently, can never
    # express a cross-array rule — it has to be a second pass here.
    #
    # No per-member field is rejected any more. `args` was never rejected:
    # the build keeps such a member as its own standalone node and the
    # runtime excludes it from the group, so the hook still runs — rejecting
    # here killed the build before either half could act (issue #1199
    # review). `body: impl.sh` was rejected until issue #1281 because the
    # dispatcher imported every member as Python; `_dispatch.run_one` now
    # runs a shell member as a subprocess under the member deadline, so a
    # shell body collapses into the group like any other member (the Stop
    # group's completion-verify and retrospect-mix-check are the live cases).
    if isinstance(manifest, dict):
        # The argv sentinel doubles as a legal matcher value (the schema
        # allows any non-empty string), and a group whose matcher IS the
        # sentinel renders the same argv as a matcher-less one — main() then
        # maps it to None and resolves zero members. JSON Schema cannot say
        # "any string except this one" in the supported subset, so the
        # exclusion lives here (issue #1199 review).
        for label, entries in (
            ("hooks", hooks_list),
            ("dispatch_groups", manifest.get("dispatch_groups", [])),
        ):
            for idx, entry in enumerate(entries):
                if not isinstance(entry, dict):
                    continue
                if entry.get("matcher") == DISPATCH_NO_MATCHER_ARG:
                    out.append(
                        f"SCHEMA hooks/manifest.json $.{label}[{idx}].matcher: "
                        f"{DISPATCH_NO_MATCHER_ARG!r} is reserved as the "
                        "matcher-less argv sentinel and cannot be a matcher"
                    )
    return out


def manifest_hosts_enum() -> list[str]:
    """The closed `hosts` value set declared in hooks/manifest.schema.json.

    Single source for valid host identifiers: platform files' host_id values
    are validated against it (load_platform), and check-plugin-manifests.py
    cross-checks the reverse direction (no stale enum value without a
    platform file).
    """
    schema = load_schema()
    return schema["properties"]["hooks"]["items"]["properties"]["hosts"][
        "items"
    ]["enum"]


def load_platform(platform_file: Path) -> dict:
    """Parse one manifests/platforms/*.json declaration with checked access.

    Raw `platform["outputs"]` / `output["path"]` indexing used to surface a
    malformed platform file as a bare KeyError traceback; this loader raises
    ValueError naming the file and the offending key instead (same diagnostic
    precedent as render_output's unknown-kind ValueError). Callers (main()
    and check-plugin-manifests.py) may then index the checked keys directly.
    """
    rel = platform_file.name
    platform = json.loads(platform_file.read_text())
    if not isinstance(platform, dict):
        raise ValueError(f"manifests/platforms/{rel}: top level must be an object")
    if not isinstance(platform.get("platform"), str):
        raise ValueError(
            f"manifests/platforms/{rel}: missing or non-string key 'platform'"
        )
    outputs = platform.get("outputs")
    if not isinstance(outputs, list):
        raise ValueError(
            f"manifests/platforms/{rel}: missing or non-array key 'outputs'"
        )
    for i, output in enumerate(outputs):
        if not isinstance(output, dict):
            raise ValueError(
                f"manifests/platforms/{rel}: outputs[{i}] must be an object"
            )
        for key in ("kind", "path"):
            if not isinstance(output.get(key), str):
                raise ValueError(
                    f"manifests/platforms/{rel}: outputs[{i}] missing or "
                    f"non-string key {key!r}"
                )
        if output["path"] == "":
            # An empty string is a str, so the isinstance check above lets it
            # through; REPO_ROOT / "" then resolves to REPO_ROOT itself, and
            # the render/check callers' read_text()/write_json() raise
            # IsADirectoryError instead of a diagnostic naming the file
            # (review round 2, Codex finding 4).
            raise ValueError(
                f"manifests/platforms/{rel}: outputs[{i}] key 'path' must "
                "not be empty"
            )
        if output["kind"] == "marketplace" and not isinstance(
            output.get("plugin_source"), str
        ):
            raise ValueError(
                f"manifests/platforms/{rel}: outputs[{i}] kind 'marketplace' "
                "requires string key 'plugin_source'"
            )
    # host_id (or its platform fallback) must be one of the closed hosts
    # values in hooks/manifest.schema.json: a typo'd host_id ("Claude") would
    # otherwise silently drop every hosts-restricted hook from this platform's
    # hooks.json — and the byte-drift check's suggested remedy (re-run the
    # build) would then commit the gutted output as the new expectation.
    host_id = platform.get("host_id", platform["platform"])
    hosts_enum = manifest_hosts_enum()
    if not isinstance(host_id, str) or host_id not in hosts_enum:
        raise ValueError(
            f"manifests/platforms/{rel}: host_id {host_id!r} is not one of the "
            f"closed hosts values {hosts_enum!r} declared in "
            "hooks/manifest.schema.json"
        )
    return platform


# ---------------------------------------------------------------------------
# hooks.json expansion
# ---------------------------------------------------------------------------

def _wrapper_filename(entry: dict) -> str:
    suffix = entry.get("wrapper_suffix", "")
    return f"{entry['name']}{suffix}.sh"


def _command_for(entry: dict) -> str:
    """Build the ${CLAUDE_PLUGIN_ROOT}/hooks/<file>.sh [args] command.

    The wrapper itself bakes in any `wrapper_suffix`-bound args (e.g.
    multi-event pre/post dispatch), so they are NOT repeated in the
    command string. Body-as-sh hooks (strike-counter etc.) have plain
    `args` and pass them on the command line.
    """
    file_name = _wrapper_filename(entry)
    base = f"${{CLAUDE_PLUGIN_ROOT}}/hooks/{file_name}"
    # If wrapper_suffix is set, args are baked into the wrapper body — do
    # not duplicate them on the command line. Otherwise, append args.
    if entry.get("wrapper_suffix"):
        return base
    args = entry.get("args") or []
    if not args:
        return base
    # shlex.quote: the command string is executed via `sh -c`, so any arg
    # carrying a shell metacharacter must be quoted (a no-op for the plain
    # words used today — see the dispatcher-node quoting note, PR #1198).
    return base + " " + " ".join(shlex.quote(a) for a in args)


def _entry_to_hook_node(entry: dict) -> dict:
    """Render a single manifest entry as a hooks.json `hook` node.

    `args_declared` is a TRANSIENT marker (like `hosts`): it never reaches a
    written hooks.json — `filter_hooks_for_host` strips it. It flags entries
    whose manifest declares `args`, which the dispatcher cannot forward
    (members are invoked with stdin only; the runtime's `group_members`
    excludes them the same way), so the collapse keeps them standalone instead
    of silently disabling them (issue #1199 review).
    """
    node: dict = {
        "type": "command",
        "command": _command_for(entry),
        "timeout": entry["timeout"],
    }
    if "hosts" in entry:
        node["hosts"] = entry["hosts"]
    if entry.get("args"):
        node["args_declared"] = True
    return node


def expand_to_hooks_json(manifest: dict) -> dict:
    """Expand manifest.hooks (flat array) into hooks.json grouped format.

    Within each event, group consecutive entries that share the same
    matcher. This reproduces the pre-Phase-2 hooks.json grouping exactly,
    so the byte-identical invariant holds when the manifest array order
    matches the historical baseline.
    """
    out: dict = {"description": manifest["description"], "hooks": {}}
    for entry in manifest["hooks"]:
        event = entry["event"]
        matcher = entry.get("matcher")
        groups = out["hooks"].setdefault(event, [])
        last = groups[-1] if groups else None
        # A new group starts when matcher changes (or last group does
        # not exist). matcher==None for non-tool events (SessionStart,
        # UserPromptSubmit, Stop, PostToolUse global).
        last_matcher = (last or {}).get("matcher") if last else None
        if last is None or last_matcher != matcher:
            new_group: dict = {}
            if matcher is not None:
                new_group["matcher"] = matcher
            new_group["hooks"] = []
            groups.append(new_group)
            last = new_group
        last["hooks"].append(_entry_to_hook_node(entry))
    return out


def _dispatcher_node(event: str, matcher: str | None, host_id: str, timeout: int) -> dict:
    """Render the single dispatch-group node (ADR-0002).

    The command bakes in the platform `host_id` so the dispatcher applies the
    same host filter at runtime (it re-reads the canonical manifest). `timeout`
    is the max member timeout: the dispatcher runs members sequentially in one
    process, so a single hanging member is bounded by the same budget the
    slowest member had under the per-process model (the rest fail open) — using
    the sum would let one hang block the tool far longer than today's parallel
    worst case.

    Every interpolated arg is shlex-quoted: the host executes this command
    string via `sh -c`, so an unquoted pipe-carrying matcher such as
    `Edit|NotebookEdit|Write` would be parsed as a 3-command PIPELINE — the
    dispatcher would run with matcher `Edit` (the wrong group) and its stdout
    (the deny JSON) would be swallowed by the pipe (PR #1198 review, critical).
    `shlex.quote` is a no-op for metacharacter-free tokens (`Bash`, host ids),
    so the pre-existing Bash group command is byte-identical.

    A matcher-less group (matcher=None) renders `DISPATCH_NO_MATCHER_ARG` in
    the matcher argv slot; `_dispatch.main()` maps it back to None. Rendering
    None directly would pass the literal "None" and resolve zero members.
    """
    matcher_arg = DISPATCH_NO_MATCHER_ARG if matcher is None else matcher
    cmd = (
        f"${{CLAUDE_PLUGIN_ROOT}}/hooks/{DISPATCH_WRAPPER_NAME} "
        f"{shlex.quote(event)} {shlex.quote(matcher_arg)} {shlex.quote(host_id)}"
    )
    return {"type": "command", "command": cmd, "timeout": timeout}


def filter_hooks_for_host(
    hooks_data: dict,
    host_id: str,
    dispatch_groups: frozenset[tuple[str, str | None]] = frozenset(),
) -> dict:
    """Return a copy of hooks_data with each entry filtered to host_id.

    An entry is kept iff its `hosts` field is absent (= all hosts) OR
    contains host_id. The `hosts` field itself is stripped from the
    output. Empty groups/events are removed.

    ADR-0002: an (event, matcher) pair in `dispatch_groups` is collapsed — after
    host filtering — to ONE dispatcher node that runs all its members in a
    single process. The manifest may split a dispatch matcher across several
    non-consecutive groups (Bash entries interleaved with Edit/Write ones), so
    the runtime dispatcher resolves ALL exact-matcher members from the manifest;
    emitting a dispatcher node per fragment would run every member N times.
    Hence exactly one node is emitted (at the first non-empty fragment) with the
    max timeout across all fragments, and the remaining fragments are dropped.
    Collapse happens here (not in expand_to_hooks_json) because the dispatcher
    command needs the per-platform host_id baked in.

    args-declaring members (transient `args_declared` marker, see
    `_entry_to_hook_node`) are NOT collapsed: the dispatcher invokes members
    with stdin only, and the runtime resolver (`_dispatch.group_members`)
    excludes them for the same reason — collapsing them here while the runtime
    skips them would fully disable the hook. They keep their standalone node
    (in their own fragment slot) and are excluded from the dispatcher budget.
    """
    filtered = copy.deepcopy(hooks_data)
    result_hooks: dict = {}
    _TRANSIENT_KEYS = ("hosts", "args_declared")
    for event_name, event_groups in filtered.get("hooks", {}).items():
        # Pre-pass: max host-kept member timeout per dispatch matcher, across
        # ALL fragments of that matcher in this event. args-declaring members
        # never run under the dispatcher, so they contribute no budget.
        dispatch_timeout: dict[str | None, int] = {}
        for group in event_groups:
            matcher = group.get("matcher")
            if (event_name, matcher) not in dispatch_groups:
                continue
            for hook in group.get("hooks", []):
                if hook.get("args_declared"):
                    continue
                hosts = hook.get("hosts")
                if hosts is None or host_id in hosts:
                    dispatch_timeout[matcher] = max(
                        dispatch_timeout.get(matcher, 0), hook["timeout"]
                    )

        emitted_dispatch: set[str | None] = set()
        kept_groups = []
        for group in event_groups:
            matcher = group.get("matcher")
            if (event_name, matcher) in dispatch_groups:
                kept_members = [
                    hook
                    for hook in group.get("hooks", [])
                    if hook.get("hosts") is None or host_id in hook.get("hosts", [])
                ]
                standalone = [h for h in kept_members if h.get("args_declared")]
                collapsible = [h for h in kept_members if not h.get("args_declared")]
                new_nodes: list[dict] = []
                # Emit the single dispatcher node at the first fragment that has
                # at least one host-kept COLLAPSIBLE member; drop the collapsed
                # members of every other fragment. The `collapsible` guard keeps
                # the node in the right slot when an earlier fragment is
                # entirely host-filtered out (or holds only args members).
                if (
                    collapsible
                    and matcher in dispatch_timeout
                    and matcher not in emitted_dispatch
                ):
                    emitted_dispatch.add(matcher)
                    new_nodes.append(
                        _dispatcher_node(
                            event_name, matcher, host_id, dispatch_timeout[matcher]
                        )
                    )
                new_nodes.extend(
                    {k: v for k, v in h.items() if k not in _TRANSIENT_KEYS}
                    for h in standalone
                )
                if new_nodes:
                    new_group = {k: v for k, v in group.items() if k != "hooks"}
                    new_group["hooks"] = new_nodes
                    kept_groups.append(new_group)
                continue

            kept = []
            for hook in group.get("hooks", []):
                hosts = hook.get("hosts")
                if hosts is None or host_id in hosts:
                    entry = {k: v for k, v in hook.items() if k not in _TRANSIENT_KEYS}
                    kept.append(entry)
            if kept:
                new_group = {k: v for k, v in group.items() if k != "hooks"}
                new_group["hooks"] = kept
                kept_groups.append(new_group)
        if kept_groups:
            result_hooks[event_name] = kept_groups
    out = {k: v for k, v in filtered.items() if k != "hooks"}
    out["hooks"] = result_hooks
    return out


# ---------------------------------------------------------------------------
# Wrapper emission
# ---------------------------------------------------------------------------

def _wrapper_body(entry: dict) -> str:
    role = entry["role"]
    name = entry["name"]
    if entry.get("body") == "impl.sh":
        return WRAPPER_SH_TEMPLATE.format(role=role, name=name)
    # Python wrapper. If wrapper_suffix is set, bake the dispatch args
    # into the wrapper body so each event leg has its own entry point.
    if entry.get("wrapper_suffix"):
        baked = entry.get("args") or []
        baked_args = "".join(f'"{a}" ' for a in baked)
    else:
        baked_args = ""
    return WRAPPER_PY_TEMPLATE.format(role=role, name=name, baked_args=baked_args)


def _wrapper_registrations(
    manifest: dict,
) -> dict[str, list[tuple[str | None, str | None, bool]]]:
    """Map each wrapper filename to every (event, matcher, has_args) it serves.

    A wrapper file is shared by all manifest entries with the same
    (name, wrapper_suffix), so the registrations must be aggregated ACROSS those
    entries. This is what makes the dispatch-only test correct for a multi-event
    hook: one registered for both Bash and AskUserQuestion still needs its wrapper
    for the (non-dispatched) AskUserQuestion leg, so it is NOT dispatch-only.
    Multi-event hooks are flat sibling entries in the manifest (one object per
    event); the hypothetical nested "entries" form had zero uses and was removed
    (issue #1169).
    """
    regs: dict[str, list[tuple[str | None, str | None, bool]]] = {}
    for entry in manifest["hooks"]:
        fname = _wrapper_filename(entry)
        regs.setdefault(fname, []).append(
            (entry.get("event"), entry.get("matcher"), bool(entry.get("args")))
        )
    return regs


def dispatch_only_wrappers(manifest: dict) -> set[str]:
    """Wrapper filenames whose every registration is collapsed into a dispatch
    group (ADR-0002 Phase 4 / #618).

    These members are invoked only through the single dispatcher
    (`_dispatch.sh`), which imports each member's `impl.py` in-process (or, for
    a `body: impl.sh` member, execs the impl as a subprocess — issue #1281) — so
    the per-member `hooks/<name>.sh` wrapper has no `hooks.json` node
    referencing it and is dead weight. `emit_wrappers` skips them and
    `check-plugin-manifests.py` (Rule 6) asserts they are absent from disk. A
    hook with any non-dispatched registration keeps its wrapper (see
    `_wrapper_registrations`). An args-declaring registration is never
    dispatch-only even inside a dispatch group: the collapse keeps its
    standalone node (see `filter_hooks_for_host`), which still execs the
    wrapper.
    """
    dispatch = frozenset(
        (g["event"], g.get("matcher")) for g in manifest.get("dispatch_groups", [])
    )
    return {
        fname
        for fname, regs in _wrapper_registrations(manifest).items()
        if regs
        and all((ev, ma) in dispatch and not has_args for ev, ma, has_args in regs)
    }


def emit_wrappers(manifest: dict) -> list[str]:
    """Generate hooks/<name>{suffix}.sh wrappers from the manifest +
    the OPT_IN_HOOKS set.

    Returns relative paths that were created or rewritten. Multiple
    manifest entries that share the same (name, wrapper_suffix) emit a
    single wrapper file (e.g. strike-counter is registered for three
    events but only needs one wrapper).
    """
    # ADR-0002 Phase 4 (#618): a member whose every registration is collapsed
    # into a dispatch group is invoked only through _dispatch.sh, so its
    # per-member wrapper is never referenced — skip it.
    skip = dispatch_only_wrappers(manifest)
    emitted: dict[str, str] = {}
    for entry in manifest["hooks"]:
        fname = _wrapper_filename(entry)
        if fname in skip:
            continue
        body = _wrapper_body(entry)
        if fname in emitted:
            if emitted[fname] != body:
                raise SystemExit(
                    f"manifest inconsistency: wrapper '{fname}' would be "
                    f"emitted with two different bodies"
                )
            continue
        emitted[fname] = body

    # Opt-in hooks: not in manifest, but their documented invocation
    # path goes through hooks/<name>.sh, so emit a wrapper anyway.
    for opt_in_name, opt_in_role in OPT_IN_HOOKS.items():
        fname = f"{opt_in_name}.sh"
        if fname in emitted:
            continue  # opt-in name collides with a manifest entry — manifest wins
        body = WRAPPER_PY_TEMPLATE.format(
            role=opt_in_role, name=opt_in_name, baked_args=""
        )
        emitted[fname] = body

    # ADR-0002: the single dispatch-runner wrapper. Dispatch-group hooks.json
    # nodes exec this (with event/matcher/host args) instead of one wrapper per
    # member. Members registered ONLY in a dispatch group no longer get their own
    # wrapper (skipped above, #618); a member also registered for a
    # non-dispatched event/matcher keeps its wrapper for that leg.
    emitted[DISPATCH_WRAPPER_NAME] = WRAPPER_DISPATCH_TEMPLATE

    changed: list[str] = []
    HOOKS_DIR.mkdir(parents=True, exist_ok=True)
    for fname, body in sorted(emitted.items()):
        out_path = HOOKS_DIR / fname
        existing = out_path.read_text() if out_path.exists() else None
        if existing != body:
            out_path.write_text(body)
            os.chmod(out_path, 0o755)
            changed.append(str(out_path.relative_to(REPO_ROOT)))
        else:
            # Ensure executable bit even when content matches.
            st = out_path.stat()
            if not (st.st_mode & 0o111):
                os.chmod(out_path, 0o755)
                changed.append(str(out_path.relative_to(REPO_ROOT)))
    return changed


def hook_identities(manifest: dict) -> dict[str, str]:
    """Map hook name -> role for every hook that owns a directory: manifest
    entries (deduped by name across multi-event registrations) plus the
    OPT_IN_HOOKS set (not in the manifest, but a real hook dir). The single
    source of truth for the per-hook docs/hook stubs (#606) and their
    byte-identity check (check Rule 15).
    """
    ids: dict[str, str] = {}
    for entry in manifest["hooks"]:
        ids[entry["name"]] = entry["role"]
    for name, role in OPT_IN_HOOKS.items():
        ids.setdefault(name, role)
    collisions = set(ids) & NON_HOOK_DOCS
    if collisions:
        raise SystemExit(
            "manifest inconsistency: hook name(s) collide with NON_HOOK_DOCS "
            f"(a hand-written doc would be shadowed by a stub): {sorted(collisions)}"
        )
    return ids


def doc_stub_body(role: str, name: str) -> str:
    """The canonical 1-line redirect stub body for docs/hook/<name>.md."""
    return DOC_STUB_TEMPLATE.format(role=role, name=name)


def emit_doc_stubs(manifest: dict) -> list[str]:
    """Generate docs/hook/<name>.md 1-line redirect stubs, one per hook dir
    (ADR-0001 §337-338, #606). Idempotent: only files whose body differs are
    rewritten. Hand-written docs (NON_HOOK_DOCS, e.g. block-message-format.md)
    are never touched — they are not hook identities.

    Returns relative paths that were created or rewritten.
    """
    changed: list[str] = []
    DOCS_HOOK_DIR.mkdir(parents=True, exist_ok=True)
    for name, role in sorted(hook_identities(manifest).items()):
        out_path = DOCS_HOOK_DIR / f"{name}.md"
        body = doc_stub_body(role, name)
        existing = out_path.read_text() if out_path.exists() else None
        if existing != body:
            out_path.write_text(body)
            changed.append(str(out_path.relative_to(REPO_ROOT)))
    return changed


# ---------------------------------------------------------------------------
# Hook operating matrix
# ---------------------------------------------------------------------------

def _md_cell(value: str) -> str:
    """Escape content for a markdown table cell."""
    return value.replace("|", "\\|").replace("\n", "<br>")


def _compact_join(values: list[str]) -> str:
    uniq = sorted({v for v in values if v})
    return ", ".join(uniq) if uniq else "-"


def _display_width(value: str) -> int:
    """East-Asian-wide-aware display width, matching markdownlint MD060."""
    return sum(2 if unicodedata.east_asian_width(ch) in ("W", "F") else 1 for ch in value)


def _render_aligned_table(header: list[str], rows: list[list[str]]) -> list[str]:
    """Render a GFM table satisfying markdownlint MD060 'aligned' style.

    Each column is padded (with a leading/trailing space inside the pipes)
    to the display width of its widest cell across header + rows.
    """
    widths = [
        max(_display_width(header[col]), *(_display_width(row[col]) for row in rows))
        if rows
        else _display_width(header[col])
        for col in range(len(header))
    ]

    def render_row(cells: list[str]) -> str:
        padded = [cell + " " * (widths[col] - _display_width(cell)) for col, cell in enumerate(cells)]
        return "| " + " | ".join(padded) + " |"

    lines = [render_row(header), "| " + " | ".join("-" * w for w in widths) + " |"]
    lines.extend(render_row(row) for row in rows)
    return lines


def _hook_events(entries: list[dict]) -> str:
    labels: list[str] = []
    for entry in entries:
        event = entry["event"]
        matcher = entry.get("matcher")
        if matcher:
            labels.append(f"{event}({matcher})")
        else:
            labels.append(event)
    return _compact_join(labels)


def _hook_hosts(entries: list[dict]) -> str:
    host_sets = {
        ",".join(entry.get("hosts") or ["all"])
        for entry in entries
    }
    return _compact_join(list(host_sets))


def _default_signal(role: str) -> str:
    if role == "preflight-gate":
        return "gate"
    if role == "advisory-nudge":
        return "advisory"
    if role == "postuse-correction":
        return "postuse"
    if role == "completion-verify":
        return "stop/session"
    return role


# ---------------------------------------------------------------------------
# Doc cross-check parsers (#688)
#
# These parse the human-readable views (docs/bypass-vars.md, SECURITY.md) so
# check-plugin-manifests.py can assert they agree with the canonical manifest
# `mode` metadata. The matrix RENDERER above reads only the manifest; these
# parsers exist solely for the drift gate, never to feed the matrix.
# ---------------------------------------------------------------------------

def _bypass_vars_section_body(section: str) -> str | None:
    """Return the markdown body of a `## <section>` block in bypass-vars.md."""
    if not BYPASS_VARS_DOC.exists():
        return None
    text = BYPASS_VARS_DOC.read_text()
    marker = f"## {section}"
    start = text.find(marker)
    if start < 0:
        return None
    next_start = text.find("\n## ", start + len(marker))
    return text[start: next_start if next_start >= 0 else len(text)]


def parse_doc_env_table(section: str, hook_names: list[str]) -> dict[str, list[str]]:
    """Map hook name -> env vars from a `## <section>` table in bypass-vars.md.

    Rows are backtick-delimited "VAR | hook | …" cells. The `_ACK` companion var
    in the Strict section is skipped (it is an unlock token, not a mode switch —
    it has no manifest `mode` field), matching the matrix's historical exclusion.
    """
    body = _bypass_vars_section_body(section)
    if body is None:
        return {}
    out: dict[str, list[str]] = {}
    for line in body.splitlines():
        if not line.startswith("| `"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 2:
            continue
        var = cells[0].strip("`")
        if section == "Strict" and var.endswith("_ACK"):
            continue
        hook_cell = cells[1]
        for hook_name in hook_names:
            if hook_name in hook_cell:
                out.setdefault(hook_name, []).append(var)
    return out


def parse_doc_state_vars(hook_names: list[str]) -> dict[str, list[str]]:
    """Map hook name -> state/path env vars from the `## Path / test` table."""
    body = _bypass_vars_section_body("Path / test")
    if body is None:
        return {}
    out: dict[str, list[str]] = {}
    for line in body.splitlines():
        if not line.startswith("| `"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 3:
            continue
        var = cells[0].strip("`")
        hook_cell = cells[2]
        for hook_name in hook_names:
            if hook_name in hook_cell:
                out.setdefault(hook_name, []).append(var)
    return out


def parse_doc_external_commands() -> dict[str, list[str]]:
    """Map hook name -> read-only external command snippets from SECURITY.md."""
    if not SECURITY_DOC.exists():
        return {}
    out: dict[str, list[str]] = {}
    for line in SECURITY_DOC.read_text().splitlines():
        if not line.startswith("| `hooks/"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        if len(cells) < 2:
            continue
        hook_path = cells[0].strip("`")
        parts = hook_path.split("/")
        if len(parts) < 3:
            continue
        hook_name = parts[2]
        command = cells[1].strip("`")
        out.setdefault(hook_name, []).append(command)
    return out


def hook_mode(entries: list[dict]) -> dict:
    """Aggregate the `mode` metadata for one hook across its manifest entries.

    `mode` is attached to a single (the first) registration of each hook name —
    multi-event hooks share one operating mode — but a defensive merge here keeps
    the matrix correct even if a future edit splits fields across entries. The
    single source of truth for a hook's strict/bypass env vars, state-path env
    vars, and read-only external commands is this manifest block (#688). The
    human-readable views in docs/bypass-vars.md and SECURITY.md are cross-checked
    against it by check-plugin-manifests.py so the two cannot drift.
    """
    merged: dict = {}
    for entry in entries:
        mode = entry.get("mode")
        if not mode:
            continue
        if "strict_env" in mode and "strict_env" not in merged:
            merged["strict_env"] = mode["strict_env"]
        for key in ("bypass_env", "state_paths", "external_commands"):
            if mode.get(key):
                merged.setdefault(key, [])
                for value in mode[key]:
                    if value not in merged[key]:
                        merged[key].append(value)
    return merged


def hook_review_by(entries: list[dict]) -> str | None:
    """The sunset-review date for one hook name, or None when none is declared.

    `review_by` is attached to the first registration of each hook name
    (multi-event siblings may omit it, mirroring `hosts`); the first
    registration that carries one wins. Well-formedness and overdue-ness
    are check-plugin-manifests.py rule 26's job — this is a plain lookup.
    """
    for entry in entries:
        value = entry.get("review_by")
        if value is not None:
            return value
    return None


def _hook_review_by(entries: list[dict]) -> str:
    return hook_review_by(entries) or ""


def render_hook_operating_matrix(manifest: dict) -> str:
    """Render a generated hook operating-surface matrix.

    The matrix is sourced entirely from structured metadata in
    hooks/manifest.json: registration shape (role, event, matcher, hosts) plus
    the per-hook `mode` block (strict env, bypass env, state-path vars, read-only
    external commands). docs/bypass-vars.md and SECURITY.md are human-readable
    views that check-plugin-manifests.py validates against this manifest, so a
    value can live in exactly one canonical place (#688).
    """
    by_name: dict[str, list[dict]] = {}
    for entry in manifest["hooks"]:
        by_name.setdefault(entry["name"], []).append(entry)

    strict_vars: dict[str, list[str]] = {}
    bypass_vars: dict[str, list[str]] = {}
    state_vars: dict[str, list[str]] = {}
    external_commands: dict[str, list[str]] = {}
    for name, entries in by_name.items():
        mode = hook_mode(entries)
        if mode.get("strict_env"):
            strict_vars[name] = [mode["strict_env"]]
        if mode.get("bypass_env"):
            bypass_vars[name] = mode["bypass_env"]
        if mode.get("state_paths"):
            state_vars[name] = mode["state_paths"]
        if mode.get("external_commands"):
            external_commands[name] = mode["external_commands"]

    header = [
        "Hook", "Role", "Events", "Hosts", "Default", "Review by",
        "Strict env", "Bypass env", "State/path vars", "External commands",
    ]
    table_rows = []
    for name in sorted(by_name):
        entries = by_name[name]
        role = entries[0]["role"]
        spec = f"[`{name}`](../hooks/{role}/{name}/spec.md)"
        table_rows.append([
            spec,
            _md_cell(role),
            _md_cell(_hook_events(entries)),
            _md_cell(_hook_hosts(entries)),
            _md_cell(_default_signal(role)),
            _md_cell(_hook_review_by(entries)),
            _md_cell(_compact_join(strict_vars.get(name, []))),
            _md_cell(_compact_join(bypass_vars.get(name, []))),
            _md_cell(_compact_join(state_vars.get(name, []))),
            _md_cell(_compact_join(external_commands.get(name, []))),
        ])

    lines = [
        "# Hook Operating Matrix",
        "",
        "<!-- AUTO-GENERATED by scripts/build-plugin-manifests.py - DO NOT EDIT -->",
        "",
        "This matrix summarizes the hook operating surface from a single",
        "structured source. Regenerate it with `./scripts/build-plugin-manifests.py`;",
        "drift is checked by `./scripts/check-plugin-manifests.py`.",
        "",
        "Source:",
        "",
        "- `hooks/manifest.json` -> role, event, matcher, hosts, the sunset-review",
        "  date `review_by` (#1300), and the per-hook `mode` block (strict env,",
        "  bypass env, state/path vars, read-only external commands).",
        "",
        "`docs/bypass-vars.md` and `SECURITY.md` are human-readable views of the",
        "same `mode` metadata; the check script validates them against the manifest",
        "so the two cannot drift. A `-` in a column means the hook declares no",
        "value for it in its manifest `mode` block.",
        "",
        *_render_aligned_table(header, table_rows),
    ]
    lines.append("")
    return "\n".join(lines)


def emit_hook_operating_matrix(manifest: dict) -> list[str]:
    body = render_hook_operating_matrix(manifest)
    existing = HOOK_OPERATING_MATRIX_PATH.read_text() if HOOK_OPERATING_MATRIX_PATH.exists() else None
    if existing == body:
        return []
    HOOK_OPERATING_MATRIX_PATH.write_text(body)
    return [str(HOOK_OPERATING_MATRIX_PATH.relative_to(REPO_ROOT))]


# ---------------------------------------------------------------------------
# Plugin / marketplace renderers (unchanged)
# ---------------------------------------------------------------------------

def render_plugin(base: dict, overrides: dict) -> dict:
    manifest = {
        "name": base["name"],
        "description": base["description"],
        "version": base["version"],
        "author": base["author"],
        "repository": base["repository"],
        "keywords": base["keywords"],
    }
    manifest.update(overrides)
    return manifest


def render_marketplace(base: dict, plugin_source: str, extras: dict | None) -> dict:
    manifest = {}
    if extras:
        manifest.update(extras)
    manifest.update({
        "name": base["name"],
        "description": base["description"],
        "owner": base["author"],
        "version": base["version"],
        "plugins": [
            {
                "name": base["name"],
                "description": base["description"],
                "version": base["version"],
                "author": base["author"],
                "source": plugin_source,
                "category": base["category"],
                "homepage": base["homepage"],
                "tags": base["keywords"],
            }
        ],
    })
    return manifest


def render_agent_plugin(base: dict) -> dict:
    """Agent Plugins 1.0.0 portable manifest (https://agent-plugins.org/).

    Written to the repo root, which is the plugin root for Claude, Cursor, and
    the spec-only clients. Codex's plugin root is plugins/praxis/, so this file
    is invisible to it — see ARCHITECTURE.md for why that is tracked separately
    rather than solved by moving this output.

    Carries spec-defined metadata only. Component paths are NOT emitted: the
    spec fixes skills at `./skills` and MCP servers at `./mcp.json`, so a
    host-specific `skills` or `hooks` key here would name a location no
    conformant client reads. Such a key does not invalidate the manifest —
    clients "report and ignore each unknown top-level field, then continue if
    the manifest is otherwise valid" — which is exactly why it must not ship:
    it would load clean and do nothing. Rule 26 in check-plugin-manifests.py
    enforces that as repo policy.
    """
    return {
        "$schema": AGENT_PLUGIN_SCHEMA_URI,
        "name": base["name"],
        "description": base["description"],
        "version": base["version"],
        "author": base["author"],
        "homepage": base["homepage"],
        "repository": base["repository"],
        "keywords": base["keywords"],
    }


def render_output(
    base: dict,
    output: dict,
    hooks_source: dict,
    host_id: str,
    dispatch_groups: frozenset[tuple[str, str | None]] = frozenset(),
) -> dict:
    kind = output["kind"]
    if kind == "plugin":
        return render_plugin(base, output.get("plugin_overrides", {}))
    if kind == "agent-plugin":
        return render_agent_plugin(base)
    if kind == "marketplace":
        return render_marketplace(
            base,
            plugin_source=output["plugin_source"],
            extras=output.get("marketplace_overrides"),
        )
    if kind == "hooks":
        return filter_hooks_for_host(hooks_source, host_id, dispatch_groups)
    raise ValueError(f"unknown output kind: {kind}")


def write_json(path: Path, data: dict) -> bool:
    """Write JSON with deterministic formatting. Return True if content changed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    existing = path.read_text() if path.exists() else None
    if existing == payload:
        return False
    path.write_text(payload)
    return True


def ensure_symlink(link: Path, target_relative: str) -> bool:
    """Create or repair `link` to point at `target_relative`. Return True on change."""
    link.parent.mkdir(parents=True, exist_ok=True)
    if link.is_symlink():
        if os.readlink(link) == target_relative:
            return False
        link.unlink()
    elif link.exists():
        raise SystemExit(
            f"refusing to replace real path with symlink: {link}. "
            "Resolve manually before re-running."
        )
    link.symlink_to(target_relative)
    return True


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    base = load_base()
    manifest = load_manifest()

    # Schema gate (#1173): the build must refuse to render from a malformed
    # manifest — otherwise a typo'd key is silently absorbed into every
    # generated artifact (and a missing key becomes a KeyError) before
    # check-plugin-manifests.py ever runs the same shared gate.
    schema_drifts = manifest_schema_drifts(manifest)
    if schema_drifts:
        for d in schema_drifts:
            print(f"ERROR {d}", file=sys.stderr)
        return 1

    hooks_source = expand_to_hooks_json(manifest)
    dispatch_groups = frozenset(
        (g["event"], g.get("matcher")) for g in manifest.get("dispatch_groups", [])
    )

    changed_paths: list[str] = []

    for platform_file in sorted(PLATFORMS_DIR.glob("*.json")):
        platform = load_platform(platform_file)
        host_id = platform.get("host_id", platform["platform"])
        for output in platform["outputs"]:
            out_path = REPO_ROOT / output["path"]
            rendered = render_output(base, output, hooks_source, host_id, dispatch_groups)
            if write_json(out_path, rendered):
                changed_paths.append(output["path"])

    # Adapter shell symlinks — Codex plugin forwards to repo-root runtime dirs.
    for name in FORWARDED_DIRS:
        link = ADAPTER_SHELL / name
        target = f"../../{name}"  # relative from plugins/praxis/<name>
        if ensure_symlink(link, target):
            changed_paths.append(str(link.relative_to(REPO_ROOT)))

    # Phase 2: runtime wrappers generated from manifest. These replace the
    # 35 hand-maintained source wrappers deleted in Phase 2 commit 2.
    changed_paths.extend(emit_wrappers(manifest))

    # docs/hook/<name>.md redirect stubs, one per hook dir (ADR-0001 §337-338, #606).
    changed_paths.extend(emit_doc_stubs(manifest))

    # Generated operating-surface matrix for hook owners and users.
    changed_paths.extend(emit_hook_operating_matrix(manifest))

    if changed_paths:
        print("wrote:")
        for p in changed_paths:
            print(f"  {p}")
    else:
        print("clean — no changes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
